/**
 * Template Domain Types
 *
 * Types related to WhatsApp message templates, including
 * template components, buttons, and workspace management.
 */

// =============================================================================
// TYPE ALIASES
// =============================================================================

/**
 * Category of a WhatsApp template.
 * Maps to Meta's template categories.
 */
export type TemplateCategory = 'MARKETING' | 'UTILIDADE' | 'AUTENTICACAO';

/**
 * Approval status of a template.
 */
export type TemplateStatus = 'DRAFT' | 'APPROVED' | 'PENDING' | 'REJECTED';

// =============================================================================
// CORE INTERFACES
// =============================================================================

/**
 * Represents a WhatsApp message template.
 */
export interface Template {
  /** Unique identifier (from Meta or local) */
  id: string;
  /** Template name (must follow Meta naming rules) */
  name: string;
  /** Template category */
  category: TemplateCategory;
  /** Language code (e.g., 'pt_BR', 'en_US') */
  language: string;
  /** Approval status */
  status: TemplateStatus;
  /** Main body content */
  content: string;
  /** Preview text for display */
  preview: string;
  /** ISO timestamp when template was last updated */
  lastUpdated: string;
  /** Parameter format used in template */
  parameterFormat?: 'positional' | 'named';
  /** Hash of template spec for change detection */
  specHash?: string | null;
  /** ISO timestamp when template was fetched from Meta */
  fetchedAt?: string | null;
  /** Media ID for header media */
  headerMediaId?: string | null;
  /** Hash of header media for change detection */
  headerMediaHash?: string | null;
  /** Preview URL for header media */
  headerMediaPreviewUrl?: string | null;
  /** ISO timestamp when preview URL expires */
  headerMediaPreviewExpiresAt?: string | null;
  /** Full component structure from Meta API */
  components?: TemplateComponent[];
}

/**
 * Component of a WhatsApp template.
 * Templates are composed of header, body, footer, and buttons.
 */
export interface TemplateComponent {
  /** Type of component */
  type: 'HEADER' | 'BODY' | 'FOOTER' | 'BUTTONS' | 'LIMITED_TIME_OFFER';
  /** Format for header components */
  format?: 'TEXT' | 'IMAGE' | 'VIDEO' | 'GIF' | 'DOCUMENT' | 'LOCATION';
  /** Text content */
  text?: string;
  /** Buttons for BUTTONS component type */
  buttons?: TemplateButton[];
  /** Example values for variables */
  example?: unknown;
  /** Limited time offer configuration */
  limited_time_offer?: {
    text: string;
    has_expiration?: boolean;
  };
}

/**
 * Button configuration in a template.
 */
export interface TemplateButton {
  /** Button type */
  type: TemplateButtonType;
  /** Button display text */
  text: string;
  /** URL for URL type buttons */
  url?: string;
  /** Phone number for PHONE_NUMBER type buttons */
  phone_number?: string;
  /** Example values for dynamic buttons */
  example?: string[] | string;
  /** OTP type for authentication templates */
  otp_type?: 'COPY_CODE' | 'ONE_TAP' | 'ZERO_TAP';
  /** Flow ID for FLOW type buttons */
  flow_id?: string;
  /** Action configuration */
  action?: Record<string, unknown>;
  /** Payload for postback buttons */
  payload?: string | Record<string, unknown>;
}

/**
 * All supported button types in WhatsApp templates.
 */
export type TemplateButtonType =
  | 'QUICK_REPLY'
  | 'URL'
  | 'PHONE_NUMBER'
  | 'COPY_CODE'
  | 'OTP'
  | 'FLOW'
  | 'CATALOG'
  | 'MPM'
  | 'VOICE_CALL'
  | 'EXTENSION'
  | 'ORDER_DETAILS'
  | 'POSTBACK'
  | 'REMINDER'
  | 'SEND_LOCATION'
  | 'SPM';

// =============================================================================
// GENERATED TEMPLATE TYPES
// =============================================================================

/**
 * Header configuration for generated templates.
 */
export interface GeneratedTemplateHeader {
  /** Header format */
  format: 'TEXT' | 'IMAGE' | 'VIDEO' | 'DOCUMENT';
  /** Text content for TEXT format */
  text?: string;
}

/**
 * Footer configuration for generated templates.
 */
export interface GeneratedTemplateFooter {
  /** Footer text content */
  text: string;
}

/**
 * Button configuration for generated templates.
 */
export interface GeneratedTemplateButton {
  /** Button type */
  type: 'QUICK_REPLY' | 'URL' | 'PHONE_NUMBER';
  /** Button display text */
  text: string;
  /** URL for URL type buttons */
  url?: string;
  /** Phone number for PHONE_NUMBER type buttons */
  phone_number?: string;
}

/**
 * Template generated by AI or batch process.
 */
export interface GeneratedTemplate {
  /** Unique identifier */
  id: string;
  /** Template name */
  name: string;
  /** Template category */
  category: string;
  /** Main content */
  content: string;
  /** Variable placeholders used */
  variables: string[];
  /** Human-readable description */
  description: string;
  /** Language code */
  language: string;
  /** Always starts as DRAFT */
  status: 'DRAFT';
  /** Header configuration */
  header?: GeneratedTemplateHeader;
  /** Footer configuration */
  footer?: GeneratedTemplateFooter;
  /** Button configurations */
  buttons?: GeneratedTemplateButton[];
  /** AI judgment result */
  judgment?: GeneratedTemplateJudgment;
  /** Whether template was auto-fixed by AI */
  wasFixed?: boolean;
}

/**
 * AI judgment result for generated templates.
 */
export interface GeneratedTemplateJudgment {
  /** Whether template was approved */
  approved: boolean;
  /** Issues found during review */
  issues: GeneratedTemplateIssue[];
  /** Original quality score */
  originalScore: number;
}

/**
 * Issue found in generated template.
 */
export interface GeneratedTemplateIssue {
  /** Description of the issue */
  reason: string;
  /** Suggested fix */
  fix?: string;
}

/**
 * Template with extended status information.
 */
export interface GeneratedTemplateWithStatus {
  /** Unique identifier */
  id: string;
  /** Template name */
  name: string;
  /** Main content */
  content: string;
  /** Current category after submission */
  category: 'UTILITY' | 'MARKETING' | 'AUTHENTICATION';
  /** Originally intended category */
  originalCategory: 'UTILITY' | 'MARKETING' | 'AUTHENTICATION';
  /** Current approval status */
  status: 'PENDING' | 'APPROVED' | 'REJECTED';
  /** Raw status from Meta API */
  metaStatus?: string;
  /** Reason for rejection if rejected */
  rejectionReason?: string;
  /** ISO timestamp when generated */
  generatedAt: string;
  /** Language code */
  language: string;
  /** Header configuration */
  header?: GeneratedTemplateHeader;
  /** Footer configuration */
  footer?: GeneratedTemplateFooter;
  /** Button configurations */
  buttons?: GeneratedTemplateButton[];
}

// =============================================================================
// WORKSPACE TYPES
// =============================================================================

/**
 * Status of a template workspace.
 */
export type WorkspaceStatus = 'draft' | 'active' | 'archived';

/**
 * Status of a template within a workspace.
 */
export type WorkspaceTemplateStatus = 'draft' | 'submitted' | 'approved' | 'rejected';

/**
 * Workspace for organizing templates.
 */
export interface TemplateWorkspace {
  /** Unique identifier */
  id: string;
  /** Display name */
  name: string;
  /** Description of the workspace */
  description?: string;
  /** Current status */
  status: WorkspaceStatus;
  /** ISO timestamp when created */
  createdAt: string;
  /** ISO timestamp when last updated */
  updatedAt: string;
  /** Number of templates in workspace */
  templateCount?: number;
  /** Summary of template statuses */
  statusSummary?: {
    draft: number;
    submitted: number;
    approved: number;
    rejected: number;
  };
}

/**
 * Template within a workspace.
 */
export interface WorkspaceTemplate {
  /** Unique identifier */
  id: string;
  /** ID of parent workspace */
  workspaceId: string;
  /** Template name */
  name: string;
  /** Main content */
  content: string;
  /** Language code */
  language: string;
  /** Template category */
  category: 'UTILITY' | 'MARKETING' | 'AUTHENTICATION';
  /** Current status in workspace */
  status: WorkspaceTemplateStatus;
  /** Meta API template ID after submission */
  metaId?: string;
  /** Status from Meta API */
  metaStatus?: 'PENDING' | 'APPROVED' | 'REJECTED';
  /** Reason for rejection */
  rejectedReason?: string;
  /** ISO timestamp when submitted to Meta */
  submittedAt?: string;
  /** ISO timestamp when created */
  createdAt: string;
  /** ISO timestamp when last updated */
  updatedAt?: string;
  /** Optional component configuration */
  components?: {
    header?: GeneratedTemplateHeader;
    footer?: GeneratedTemplateFooter;
    buttons?: GeneratedTemplateButton[];
  };
}

// =============================================================================
// PROJECT TYPES
// =============================================================================

/**
 * Status of a template project.
 */
export type ProjectStatus = 'draft' | 'submitted' | 'completed';

/**
 * Project for batch template creation.
 */
export interface TemplateProject {
  /** Unique identifier */
  id: string;
  /** Project title */
  title: string;
  /** AI prompt or description used to generate templates */
  prompt: string;
  /** Current status */
  status: ProjectStatus;
  /** Source of templates (ai, manual, etc.) */
  source?: 'ai' | 'manual' | string;
  /** Total number of templates in project */
  template_count: number;
  /** Number of approved templates */
  approved_count: number;
  /** User ID of creator */
  user_id?: string | null;
  /** ISO timestamp when created */
  created_at: string;
  /** ISO timestamp when last updated */
  updated_at: string;
}

/**
 * Individual template within a project.
 */
export interface TemplateProjectItem {
  /** Unique identifier */
  id: string;
  /** ID of parent project */
  project_id: string;
  /** Template name */
  name: string;
  /** Main content */
  content: string;
  /** Meta API template ID after submission */
  meta_id?: string;
  /** Status from Meta API */
  meta_status?: string;
  /** Header configuration */
  header?: unknown;
  /** Footer configuration */
  footer?: unknown;
  /** Button configurations */
  buttons?: unknown;
  /** Template category */
  category?: string;
  /** Language code */
  language: string;
  /** ISO timestamp when created */
  created_at: string;
  /** ISO timestamp when last updated */
  updated_at: string;
}

/**
 * Data transfer object for creating a template project.
 */
export interface CreateTemplateProjectDTO {
  /** Project title */
  title: string;
  /** AI prompt or description */
  prompt: string;
  /** Initial status */
  status?: string;
  /** Templates to create with the project */
  items: Omit<TemplateProjectItem, 'id' | 'project_id' | 'created_at' | 'updated_at'>[];
}

// =============================================================================
// BATCH SUBMISSION TYPES
// =============================================================================

/**
 * Batch submission for multiple templates.
 */
export interface BatchSubmission {
  /** Unique identifier */
  id: string;
  /** Display name (e.g., "Aviso Aula 10/12") */
  name: string;
  /** ISO timestamp when created */
  createdAt: string;
  /** Current status */
  status: 'processing' | 'completed' | 'partial_error';
  /** Submission statistics */
  stats: BatchSubmissionStats;
  /** Templates in this submission */
  templates: GeneratedTemplateWithStatus[];
}

/**
 * Statistics for a batch submission.
 */
export interface BatchSubmissionStats {
  /** Total templates in batch */
  total: number;
  /** Utility category templates */
  utility: number;
  /** Marketing category templates */
  marketing: number;
  /** Utility templates pending poll check */
  poll_utility: number;
  /** Rejected templates */
  rejected: number;
  /** Pending templates */
  pending: number;
}

// =============================================================================
// SERVICE TYPES
// =============================================================================

/**
 * Category types for utility templates.
 */
export type UtilityCategory =
  | 'order_confirmation'
  | 'shipping_update'
  | 'delivery_notification'
  | 'payment_reminder'
  | 'appointment_reminder'
  | 'account_update'
  | 'ticket_status'
  | 'subscription_update'
  | 'feedback_request'
  | 'verification_code'
  | 'password_reset'
  | 'security_alert'
  | 'reservation_confirmation'
  | 'service_completion'
  | 'document_ready';

/**
 * Parameters for generating utility templates.
 */
export interface GenerateUtilityParams {
  /** Description/prompt for AI generation */
  prompt: string;
  /** Number of templates to generate */
  quantity?: number;
  /** Language for generated templates */
  language?: 'pt_BR' | 'en_US' | 'es_ES';
}

/**
 * Response from utility template generation.
 */
export interface GenerateUtilityResponse {
  /** Generated templates */
  templates: GeneratedTemplate[];
  /** Metadata about the generation */
  metadata: {
    /** Original prompt */
    prompt: string;
    /** Number of templates requested */
    quantity: number;
    /** Language used */
    language: string;
    /** AI-suggested title for the batch */
    suggestedTitle?: string;
  };
}
